name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'
      # Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Build the Flutter web project
      - name: Build Flutter Web
        run: flutter build web

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PARAGON_GUIDE }}
          channelId: live
          projectId: paragon-guide
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks